### ISSUE TITLE
Switch off persistent mode

### ISSUE THREAD

**Issue by jasonlaw** [rapido-mobile/rapido-flutter#117]
May I know how to switch off the persistent mode, since I don't keep data locally. All my data should coming from the web api.

Thanks in advance.

**Comment by rickspencer3** [comment]
I am working on a rather large branch that supports this, but, perhaps I can do something simpler and faster for you.

**Comment by jasonlaw** [comment]
Thank you very much, really appreciate it.

**Comment by rickspencer3** [comment]
I've updated to 0.1.8 which adds the ability to turn off persistence by setting a null PersistenceProvider. I'll work on some examples later.

```
DocumentList("myDocType", persistenceProvider:null);
```

That should create a DocumentList that does not persist the data locally.
