### ISSUE TITLE
Boolean field not supported by Parse persistence provider 

### ISSUE THREAD

**Issue by jeanmarcp** [rapido-mobile/rapido-flutter#120]
Hi,

When using the Parse persistance, the boolean field type is not supported
because of the "?" at the end of the name of the field.
With this label : "Available": "available?" in the documentList, Parse send this error 
╭-- Parse Response
Class: Products
Function: ParseApiRQ.create
Status Code: 105
Type: InvalidKeyName
Error: Invalid field name: available?.
╰--  

My Parse server is hosted on back4app.

**Comment by rickspencer3** [comment]
Oh Hi! I did not realize anyone was using this or I would have helped, I'm really sorry. I have been away from this project for a while due to real work. I am currently catching up all of the out of date dependencies, testing that everything still works, then I will get back to Parse support.

**Comment by rickspencer3** [comment]
I pulled the Parse support out of the project so I could work on it in a branch for a while. If are willing and able to help, please let me know.
