### ISSUE TITLE
Dependencies out of date - new version coming soon?

### ISSUE THREAD

**Issue by macrotech5** [rapido-mobile/rapido-flutter#124]
Because rapido >=0.1.9 depends on path_provider ^0.5.0+1 and rapido <0.1.9 depends on path_provider ^0.4.1, every version of rapido requires path_provider ^0.4.1 or ^0.5.0+1.

Any chance of a new release please?

**Comment by rickspencer3** [comment]
I just made a new release that updated all the dependencies :)

**Comment by macrotech5** [comment]
Brilliant. Many thanks Rick, Rapido is back in use in my app.

**Comment by rickspencer3** [comment]
Please file and issues that you find. The dependencies changed a lot, so there may be bugs I want able to find yet.

**Comment by macrotech5** [comment]
Ok, will do.
