### ISSUE TITLE
backend

### ISSUE THREAD

**Issue by gedw99** [rapido-mobile/rapido-flutter#8]
I like this project and its very useful for apps where you have many of Master Detail forms to do CRUD on.

For the backend do you have thoughts yet ?

I have lately been using GraphQL flutter with graphQL backend in golang and getting good results in term of low friction for devs.
https://github.com/zino-app/graphql-flutter

https://github.com/zino-app/graphql-flutter#roadmap
- has subscriptions, but i still need to get it working with golang backend using gqlgen

**Comment by rickspencer3** [comment]
Assuming that by "backend" you mean something like storing documents in the cloud, I was thinking that we would create:

1. An API somewhere that manages user logins and document storage.
2. That API would be a thin wrapper over mongo, some other database, or some cloud service's document storage.
3. Client code that makes it dead simple to integrate cloud storage into DocumentList. (DocumentList.sync(), etc...)
4. Tools that make it dead simple to set up a dev account and then a production account for that backend.

I would be very glad to collaborate on this.

**Comment by rickspencer3** [comment]
I'm closing this discussion. Feel free to reopen if you want to discuss
