### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by gedw99** [rapido-mobile/rapido-flutter#9]
Can you make the example proper Flutter project ?

**Comment by rickspencer3** [comment]
Just to clarify, you mean a different main.dart file that shows all the different configuration and such? I'll go ahead and add one today.

**Comment by rickspencer3** [comment]
I merged in 2 examples. One to show all the options for DocumentViewScaffold, and one to show a custom builder.

Let me know if that suits. There are no examples yet for:
1. DocumentForm
2. DocumentList by itself
3. FloatingAddDocumentActionButton

Let me know if you think it is important to add those. They are covered in the README
